name=input("请输入您的姓名: ")
sex=input("请输入您的性别: ")
age=input("请输入您的年龄: ") 
school=input("请输入您的学校: ")
print("请稍等昂，正在生成您的简历......")
import time
time.sleep(3)
print(("%"+"$")*20)
print("姓名: "+name)
print("性别: "+sex)
print("年龄: "+age)
print("学校: "+school)
input()
print( '''     感谢使用                 '''       )